[build]
command = "react-router build"
publish = "build/client"

[build.environment]
NODE_VERSION = "22"

[dev]
command = "react-router dev"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
